
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
