create table assistants (force_use_documents boolean, id bigint generated by default as identity, tools varchar(1024), description varchar(10240), name varchar(255), primary key (id));
create table chats (assistant_id bigint, id bigint generated by default as identity, user_id bigint, name varchar(255), primary key (id));
create table document_segments (document_id bigint, id bigint generated by default as identity, embedding varchar(10240), metadata varchar(10240), text varchar(10240), primary key (id));
create table documents (assistant_id bigint, id bigint generated by default as identity, description varchar(1024), metadata varchar(10240), name varchar(255), title varchar(255), primary key (id));
create table messages (chat_id bigint, id bigint generated by default as identity, content varchar(10240), primary key (id));
create table users (id bigint generated by default as identity, openai_api_key varchar(1024), description varchar(10240), authorities varchar(255), name varchar(255), password varchar(255), username varchar(255), primary key (id));

alter table chats add constraint FKcrtcdnb2nstnm3x0k8r9w9jc7 foreign key (assistant_id) references assistants;
alter table chats add constraint FKmolqi1xj49bg3jjr33674limy foreign key (user_id) references users;
alter table document_segments add constraint FKelpq7bpa5elnst6i7tjj7m9mb foreign key (document_id) references documents;
alter table documents add constraint FKogfgjv1eiv292db0kc1knhdd1 foreign key (assistant_id) references assistants;
alter table messages add constraint FK64w44ngcpqp99ptcb9werdfmb foreign key (chat_id) references chats;
